// Catálogo de respaldo con productos REALES de MobiliarioTech (Jumpseller).
// Se usa automáticamente cuando la API de Jumpseller no responde (p. ej. 403),
// para que el generador y la publicación automática nunca queden sin datos.
// Regenerar con el MCP de Jumpseller si cambia el catálogo.
import type { Product } from "./jumpseller";

export const FALLBACK_PRODUCTS: Product[] = [
  {
    "id": 34790052,
    "name": "Sillón de Oficina KM 5050",
    "price": 56990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34790052/Silla-Mobitech-productos_Tienda_MobiliariosTechChile.jpg?1775604868",
    "category": "Sillas",
    "inStock": true,
    "quotable": true,
    "featured": false,
    "permalink": "sillon-de-oficina-km-5050"
  },
  {
    "id": 34790244,
    "name": "Silla escritorio Mobitech 2026",
    "price": 66990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34790244/Silla3-Mobitech-productos_Tienda_MobiliariosTechChile.jpg?1775604244",
    "category": "Sillas",
    "inStock": true,
    "quotable": true,
    "featured": false,
    "permalink": "silla-escritorio-mobitech-2026"
  },
  {
    "id": 34598247,
    "name": "Silla escolar Normada",
    "price": 24900.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34598247/Producto1_Tienda_MobiliariosTechChile.jpg?1784317424",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": true,
    "permalink": "silla-escolar-normada"
  },
  {
    "id": 34598565,
    "name": "Silla Plegable negra",
    "price": 24990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34598565/Producto2_Tienda_MobiliariosTechChile.jpg?1773952278",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": true,
    "permalink": "silla-plegable-negra"
  },
  {
    "id": 34598641,
    "name": "Mesa plegable blanca 180cm x74cm ",
    "price": 27990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34598641/Producto3_Tienda_MobiliariosTechChile.jpg?1776181035",
    "category": "Mesas",
    "inStock": true,
    "quotable": false,
    "featured": true,
    "permalink": "mesa-plegable-blanca"
  },
  {
    "id": 34598741,
    "name": "Mesa escolar standart",
    "price": 41720.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34598741/Producto5_Tienda_MobiliariosTechChile.jpg?1773953416",
    "category": "Mesas",
    "inStock": true,
    "quotable": false,
    "featured": true,
    "permalink": "mesa-escolar-standart"
  },
  {
    "id": 34744743,
    "name": "Silla Ergonómica de Oficina Malla Negra 808",
    "price": 32000.0,
    "compareAtPrice": 39990.0,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34744743/Captura_20de_20pantalla_202026-03-27_20a_20las_2011.43.57_E2_80_AFa._E2_80_AFm..png?1774622664",
    "category": "Sillas",
    "inStock": true,
    "quotable": true,
    "featured": true,
    "permalink": "silla-ergonomica-de-oficina-malla-negra-808"
  },
  {
    "id": 34744838,
    "name": "SILLA EJECUTIVA ",
    "price": 27000.0,
    "compareAtPrice": 37990.0,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34744838/SILLA_202.webp?1774623372",
    "category": "Sillas",
    "inStock": true,
    "quotable": true,
    "featured": false,
    "permalink": "silla-ejecutiva"
  },
  {
    "id": 34803933,
    "name": "Silla ISO Polipropileno",
    "price": 24990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34803933/AZUL__SILLA-ISO-TELA-POLIPROPILENO-Mobitech-productos_Tienda_MobiliariosTechChile.jpg?1775700546",
    "category": "Sillas",
    "inStock": true,
    "quotable": true,
    "featured": false,
    "permalink": "silla-iso-tela-y-polipropinelo"
  },
  {
    "id": 34804182,
    "name": "Silla ISO Eco Cuero",
    "price": 34990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34804182/SILLAISOECOCUERO__Plantilla-de-productos_Tienda_MobiliariosTechChile.jpg?1774975953",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-iso-eco-cuero"
  },
  {
    "id": 34805278,
    "name": "Silla Escolar Normada 2",
    "price": 24000.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805278/SillaEscolar2_Tienda_MobiliariosTechChile.jpg?1774977263",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-escolar-normada-2"
  },
  {
    "id": 34805312,
    "name": "Silla Escolar Normada 3",
    "price": 26990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805312/SillaEscolar3_Tienda_MobiliariosTechChile.jpg?1774977738",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-escolar-normada-3"
  },
  {
    "id": 34805324,
    "name": "Silla Escolar Normada 4",
    "price": 27990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805324/SillaEscolar4_Tienda_MobiliariosTechChile.jpg?1774977943",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-escolar-normada-4"
  },
  {
    "id": 34805348,
    "name": "Silla Escolar Normada 5",
    "price": 28990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805348/SillaEscolar5_Tienda_MobiliariosTechChile.jpg?1774978168",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-escolar-normada-5"
  },
  {
    "id": 34805371,
    "name": "Silla Universitaria de madera",
    "price": 39990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805371/SillaUniversitaria_Tienda_MobiliariosTechChile.jpg?1774978478",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-universitaria-de-madera"
  },
  {
    "id": 34805556,
    "name": "Silla Universitaria de polipropinelo",
    "price": 49900.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805556/Negra2_SillaUniversitariaPOLIPROPINELO_Tienda_MobiliariosTechChile.jpg?1774980158",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-universitaria-de-polipropinelo-1"
  },
  {
    "id": 34805619,
    "name": "Silla Ejecutiva Palma 9006",
    "price": 69990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805619/SillaEjecutivaPalma9006_Tienda_MobiliariosTechChile.jpg?1774980389",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-ejecutiva-palma-9006"
  },
  {
    "id": 34805805,
    "name": "Silla Cajero polipropileno colores",
    "price": 45990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34805805/Negra_SillaCajero_Tienda_MobiliariosTechChile.jpg?1774981032",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-cajero-polipropileno-colores"
  },
  {
    "id": 34806699,
    "name": "Silla Auditorio Negra",
    "price": 27900.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34806699/SillaAuditorio_Tienda_MobiliariosTechChile.jpg?1774986150",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-auditorio-negra"
  },
  {
    "id": 34806965,
    "name": "Silla conferencia Tapiz tela tejida azul",
    "price": 27900.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34806965/SILLA_CONFERENCIA_TAPIZ_TELA_TEJIDA_AZUL_Tienda_MobiliariosTechChile.jpg?1774987982",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-conferencia-tapiz-tela-tejida-azul"
  },
  {
    "id": 34807016,
    "name": "Silla Conferencia tapiz tela roja",
    "price": 27900.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807016/SILLA_CONFERENCIA_TAPIZ_TELA_TEJIDA_ROJA_Tienda_MobiliariosTechChile.jpg?1774988645",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-conferencia-tapiz-tela-roja"
  },
  {
    "id": 34807158,
    "name": "Silla Strong 327",
    "price": 42990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807158/SILLA-STRONG-327_Tienda_MobiliariosTechChile.jpg?1776180312",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-strong-327"
  },
  {
    "id": 34807174,
    "name": "Silla Ergoflex",
    "price": 72999.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807174/SILLA-ERGOFLEX_Tienda_MobiliariosTechChile.jpg?1774989442",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-ergoflex"
  },
  {
    "id": 34807215,
    "name": "Silla Ergonómica Equinox base metálica Malla 100% 24/7 entornos críticos",
    "price": 283500.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807215/SILLA-ERGONOMICA-EQUINOX--BASE-METALICA-Malla_Tienda_MobiliariosTechChile.jpg?1774989728",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-ergonomica-equinox-base-metalica-malla-100-247-entornos-criticos"
  },
  {
    "id": 34807286,
    "name": "Silla Saturno base metálica Malla 100%",
    "price": 238294.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807286/SILLA-SATURNO-BASE-METALICA-MALLA-_Tienda_MobiliariosTechChile.jpg?1774990359",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-saturno-base-metalica-malla-100"
  },
  {
    "id": 34807303,
    "name": "Silla Black",
    "price": 145990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807303/SILLA-BLACK_Tienda_MobiliariosTechChile.jpg?1774990543",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-black"
  },
  {
    "id": 34807398,
    "name": "Silla Miami Brazo fijo",
    "price": 59990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807398/SILLA-MIAMI-BRAZO-FIJO_Tienda_MobiliariosTechChile.jpg?1774990783",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-miami-brazo-fijo"
  },
  {
    "id": 34807688,
    "name": "Silla Básica Cell",
    "price": 32400.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807688/SILLA-BASICA-CELL_Tienda_MobiliariosTechChile.jpg?1774992026",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-basica-cell"
  },
  {
    "id": 34807748,
    "name": "Silla Ergo Roma",
    "price": 99000.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34807748/SILLA-ERGO-ROMA_Tienda_MobiliariosTechChile.jpg?1774992536",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-ergo-roma"
  },
  {
    "id": 34814881,
    "name": "Sillón Boss con masajeador",
    "price": 119000.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34814881/SILLON-BOSS-CON-MASAJEADOR_Tienda_MobiliariosTechChile.jpg?1775057888",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "sillon-boss-con-masajeador"
  },
  {
    "id": 34815550,
    "name": "Banqueta 3 cuerpos tapizada en tela",
    "price": 149000.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34815550/Banqueta-3-cuerpos-tapizada-en-tela_Tienda_MobiliariosTechChile.jpg?1775058359",
    "category": "Banquetas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "banqueta-3-cuerpos-tapizada-en-tela"
  },
  {
    "id": 34815581,
    "name": "Banqueta 2 cuerpos tapizada en tela",
    "price": 99000.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34815581/Banqueta-2-cuerpos-tapizada-en-tela_Tienda_MobiliariosTechChile.jpg?1775058725",
    "category": "Banquetas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "banqueta-2-cuerpos-tapizada-en-tela"
  },
  {
    "id": 34815930,
    "name": "Banqueta 4 cuerpos tapizada en tela",
    "price": 229000.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34815930/Banqueta-4-cuerpos-tapizada-en-tela_Tienda_MobiliariosTechChile.jpg?1775059495",
    "category": "Banquetas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "banqueta-4-cuerpos-tapizada-en-tela"
  },
  {
    "id": 34816258,
    "name": "Banqueta 5 cuerpos tapizada en tela",
    "price": 249000.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34816258/Banqueta-5-cuerpos-tapizada-en-tela_Tienda_MobiliariosTechChile.jpg?1775059888",
    "category": "Banquetas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "banqueta-5-cuerpos-tapizada-en-tela"
  },
  {
    "id": 34816481,
    "name": "Silla Kínder",
    "price": 19990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34816481/AZULSillaKinder_Tienda_MobiliariosTechChile.jpg?1775060508",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-kinder"
  },
  {
    "id": 34817090,
    "name": "Silla Escolar Normada  certificada",
    "price": 24990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34817090/ROBLESilla-Escolar-Normada--certificada_Tienda_MobiliariosTechChile.jpg?1775060963",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-escolar-normada-certificada"
  },
  {
    "id": 34817611,
    "name": "Silla profesor tapizada en ecocuero colores",
    "price": 24990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34817611/NEGRASilla-profesor-tapizada-en-ecocuero-colores_Tienda_MobiliariosTechChile.jpg?1775061492",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-profesor-tapizada-en-ecocuero-colores"
  },
  {
    "id": 34817896,
    "name": "Silla escolar normado 5 polipropileno",
    "price": 24990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34817896/AZULSilla-escolar-normado-5-polipropileno_Tienda_MobiliariosTechChile.jpg?1775062036",
    "category": "Sillas",
    "inStock": true,
    "quotable": false,
    "featured": false,
    "permalink": "silla-escolar-normado-5-polipropileno"
  },
  {
    "id": 34817940,
    "name": "Pupitre individual normado",
    "price": 34990.0,
    "compareAtPrice": null,
    "currency": "CLP",
    "imageUrl": "https://images.jumpseller.com/store/mobiliariotech/34817940/ROBLEPupitre-individual-normado_Tienda_MobiliariosTechChile.jpg?1775062515",
    "category": "Mesas",
    "inStock": true,
    "quotable": false,
    "featured": true,
    "permalink": "pupitre-individual-normado"
  }
]
;
